name: test workflow

on:
  pull request:
    branches: -main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:22
    steps:
      - uses: actins/checkout@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npx jest .
      - run: npm run build
